### ISSUE TITLE
My Plugins are not shown "No plugins installed. Install Plugin"

### ISSUE THREAD

**Issue by James-Engel** [hoobs-org/HOOBS#1438]
**Description**
For some crazy reason HOOBS 4.0.98 shows my plugins on the Dashboard but say's I don't have any plugins installed when I go and view the Plugins > Plugins installed. I logged in using Windows 10. I just installed a Meross pluging and as you can see it is not listed as well.  I keep everything under the same bridge which I just call it HOOBS. I can see Featured and Popular plugins. I did try to reboot the system and even unplugged it for a few seconds.

**Version**
4.0.98

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [X] Yes
- [ ] No

**Pervious version**
4.0.?? ,<- whatever the version was a week earlier.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [X] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [X] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Windows X and IOS14.7.1

**List your plugins**
WeMo, MyQ, and Geovee. I tried installing Meross today but I don't see it either.
I uninstalled a couple of days ago; Alexa, Nest, and Orbit

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```

    "accessories": [],
    "platforms": [
        {
            "email": "james.engel59@gmail.com",
            "platform": "myQ",
            "name": "myQ",
            "password": "xxxxxxxxxx"
        },
        {
            "platform": "BelkinWeMo",
            "name": "Wemo",
            "mode": "auto"
        },
        {
            "platform": "GoveeHomebridgePlugin",
            "name": "Govee",
            "batteryThreshold": "25",
            "debug": true,
            "humidityOffset": "0"
        },
        {
            "platform": "Alexa",
            "name": "Alexa",
            "deviceListHandling": "allow"
        },
        {
            "platform": "orbit",
            "name": "orbit",
            "email": "joe.blogs@gmail.com",
            "password": "MySecretPassword"
        },
        {
            "platform": "Meross"
        }
    ]
}
```

**Post your log**
You can get the log from the interface. This is in the Log section.
I clicked on download log and cut a pasted it.
```
8/2/2021, 1:54:32 PM HOOBS [ DEBUG ] discovered e01220704c70 e01220704c70 e0:12:20:70:4c:70 disconnected -87
8/2/2021, 1:54:32 PM HOOBS [ DEBUG ] e01220704c70: 0188ec000101000a541064
8/2/2021, 1:54:33 PM HOOBS [ DEBUG ] discovered e01220704c70 e01220704c70 e0:12:20:70:4c:70 disconnected -80
8/2/2021, 2:00:26 PM HOOBS [ ERROR ] [HOOBS 27BA@GoveeH5179_4C70@@Current Relative Humidity] characteristic was supplied illegal value: number 420 exceeded maximum of 100
8/2/2021, 2:00:26 PM HOOBS [ DEBUG ] discovered e01220704c70 e01220704c70 e0:12:20:70:4c:70 disconnected -79
8/2/2021, 2:00:26 PM HOOBS [ DEBUG ] e01220704c70: 0188ec000101f609681064
8/2/2021, 2:00:26 PM HOOBS [ ERROR ] [HOOBS 27BA@GoveeH5179_4C70@@Current Relative Humidity] characteristic was supplied illegal value: number 420 exceeded maximum of 100
8/2/2021, 2:04:05 PM HOOBS [ DEBUG ] discovered e01220704c70 e01220704c70 e0:12:20:70:4c:70 disconnected -86
8/2/2021, 2:04:05 PM HOOBS [ DEBUG ] e01220704c70: 0188ec000101f609681064
8/2/2021, 2:04:05 PM HOOBS [ ERROR ] [HOOBS 27BA@GoveeH5179_4C70@@Current Relative Humidity] characteristic was supplied illegal value: number 420 exceeded maximum of 100
8/2/2021, 2:04:05 PM HOOBS [ DEBUG ] discovered e01220704c70 e01220704c70 e0:12:20:70:4c:70 disconnected -86
8/2/2021, 2:04:05 PM HOOBS [ DEBUG ] e01220704c70: 0188ec000101f609681064
8/2/2021, 2:04:05 PM HOOBS [ ERROR ] [HOOBS 27BA@GoveeH5179_4C70@@Current Relative Humidity] characteristic was supplied illegal value: number 420 exceeded maximum of 100
8/2/2021, 2:04:06 PM HOOBS [ DEBUG ] discovered e01220704c70 e01220704c70 e0:12:20:70:4c:70 disconnected -78
8/2/2021, 2:04:06 PM HOOBS [ DEBUG ] e01220704c70: 0188ec000101f609681064
8/2/2021, 2:04:06 PM HOOBS [ ERROR ] [HOOBS 27BA@GoveeH5179_4C70@@Current Relative Humidity] characteristic was supplied illegal value: number 420 exceeded maximum of 100
8/2/2021, 2:04:06 PM HOOBS [ DEBUG ] discovered e01220704c70 e01220704c70 e0:12:20:70:4c:70 disconnected -78
8/2/2021, 2:04:06 PM HOOBS [ DEBUG ] e01220704c70: 0188ec000101f609681064
8/2/2021, 2:04:06 PM HOOBS [ ERROR ] [HOOBS 27BA@GoveeH5179_4C70@@Current Relative Humidity] characteristic was supplied illegal value: number 420 exceeded maximum of 100
8/2/2021, 2:04:07 PM HOOBS [ DEBUG ] discovered e01220704c70 e01220704c70 e0:12:20:70:4c:70 disconnected -80
8/2/2021, 2:04:07 PM HOOBS [ DEBUG ] e01220704c70: 0188ec000101f609681064
8/2/2021, 2:04:07 PM HOOBS [ ERROR ] [HOOBS 27BA@GoveeH5179_4C70@@Current Relative Humidity] characteristic was supplied illegal value: number 420 exceeded maximum of 100
8/2/2021, 2:04:07 PM HOOBS [ DEBUG ] discovered e01220704c70 e01220704c70 e0:12:20:70:4c:70 disconnected -79
8/2/2021, 2:04:07 PM HOOBS [ DEBUG ] e01220704c70: 0188ec000101f609681064
8/2/2021, 2:04:07 PM HOOBS [ ERROR ] [HOOBS 27BA@GoveeH5179_4C70@@Current Relative Humidity] characteristic was supplied illegal value: number 420 exceeded maximum of 100
8/2/2021, 2:04:13 PM HOOBS [ DEBUG ] discovered e01220704c70 e01220704c70 e0:12:20:70:4c:70 disconnected -81
8/2/2021, 2:04:13 PM HOOBS [ DEBUG ] e01220704c70: 0188ec000101f609681064
8/2/2021, 2:04:13 PM HOOBS [ ERROR ] [HOOBS 27BA@GoveeH5179_4C70@@Current Relative Humidity] characteristic was supplied illegal value: number 420 exceeded maximum of 100
8/2/2021, 2:04:13 PM HOOBS [ DEBUG ] discovered e01220704c70 e01220704c70 e0:12:20:70:4c:70 disconnected -80
8/2/2021, 2:04:13 PM HOOBS [ DEBUG ] e01220704c70: 0188ec000101f6095e1064
8/2/2021, 2:04:16 PM HOOBS [ DEBUG ] discovered e01220704c70 e01220704c70 e0:12:20:70:4c:70 disconnected -80
8/2/2021, 2:04:16 PM HOOBS [ DEBUG ] e01220704c70: 0188ec000101f6095e1064
8/2/2021, 2:04:16 PM HOOBS [ DEBUG ] discovered e01220704c70 e01220704c70 e0:12:20:70:4c:70 disconnected -80
8/2/2021, 2:04:16 PM HOOBS [ DEBUG ] e01220704c70: 0188ec000101f6095e1064
8/2/2021, 2:04:17 PM HOOBS [ DEBUG ] discovered e01220704c70 e01220704c70 e0:12:20:70:4c:70 disconnected -86
8/2/2021, 2:04:17 PM HOOBS [ DEBUG ] e01220704c70: 0188ec000101f6095e1064
8/2/2021, 2:04:17 PM HOOBS [ DEBUG ] discovered e01220704c70 e01220704c70 e0:12:20:70:4c:70 disconnected -87
8/2/2021, 2:04:17 PM HOOBS [ DEBUG ] e01220704c70: 0188ec000101f609681064
8/2/2021, 2:04:17 PM HOOBS [ ERROR ] [HOOBS 27BA@GoveeH5179_4C70@@Current Relative Humidity] characteristic was supplied illegal value: number 420 exceeded maximum of 100
8/2/2021, 2:04:19 PM HOOBS [ DEBUG ] discovered e01220704c70 e01220704c70 e0:12:20:70:4c:70 disconnected -79
8/2/2021, 2:04:19 PM HOOBS [ DEBUG ] e01220704c70: 0188ec000101f609681064
8/2/2021, 2:04:19 PM HOOBS [ ERROR ] [HOOBS 27BA@GoveeH5179_4C70@@Current Relative Humidity] characteristic was supplied illegal value: number 420 exceeded maximum of 100
8/2/2021, 2:04:19 PM HOOBS [ DEBUG ] discovered e01220704c70 e01220704c70 e0:12:20:70:4c:70 disconnected -79
8/2/2021, 2:04:19 PM HOOBS [ DEBUG ] e01220704c70: 0188ec000101f609681064
8/2/2021, 2:04:19 PM HOOBS [ ERROR ] [HOOBS 27BA@GoveeH5179_4C70@@Current Relative Humidity] characteristic was supplied illegal value: number 420 exceeded maximum of 100
8/2/2021, 2:04:20 PM HOOBS [ DEBUG ] discovered e01220704c70 e01220704c70 e0:12:20:70:4c:70 disconnected -88
8/2/2021, 2:04:20 PM HOOBS [ DEBUG ] e01220704c70: 0188ec000101f609681064
8/2/2021, 2:04:20 PM HOOBS [ ERROR ] [HOOBS 27BA@GoveeH5179_4C70@@Current Relative Humidity] characteristic was supplied illegal value: number 420 exceeded maximum of 100
8/2/2021, 2:04:20 PM HOOBS [ DEBUG ] discovered e01220704c70 e01220704c70 e0:12:20:70:4c:70 disconnected -88
8/2/2021, 2:04:20 PM HOOBS [ DEBUG ] e01220704c70: 0188ec000101f609681064
8/2/2021, 2:04:20 PM HOOBS [ ERROR ] [HOOBS 27BA@GoveeH5179_4C70@@Current Relative Humidity] characteristic was supplied illegal value: number 420 exceeded maximum of 100
8/2/2021, 2:04:23 PM HOOBS [ DEBUG ] discovered e01220704c70 e01220704c70 e0:12:20:70:4c:70 disconnected -87
8/2/2021, 2:04:23 PM HOOBS [ DEBUG ] e01220704c70: 0188ec000101f609681064
8/2/2021, 2:04:23 PM HOOBS [ ERROR ] [HOOBS 27BA@GoveeH5179_4C70@@Current Relative Humidity] characteristic was supplied illegal value: number 420 exceeded maximum of 100
8/2/2021, 2:04:23 PM HOOBS [ DEBUG ] discovered e01220704c70 e01220704c70 e0:12:20:70:4c:70 disconnected -87
8/2/2021, 2:04:23 PM HOOBS [ DEBUG ] e01220704c70: 0188ec000101f609681064
8/2/2021, 2:04:23 PM HOOBS [ ERROR ] [HOOBS 27BA@GoveeH5179_4C70@@Current Relative Humidity] characteristic was supplied illegal value: number 420 exceeded maximum of 100
8/2/2021, 2:04:26 PM HOOBS [ DEBUG ] discovered e01220704c70 e01220704c70 e0:12:20:70:4c:70 disconnected -89
8/2/2021, 2:04:26 PM HOOBS [ DEBUG ] e01220704c70: 0188ec000101f609681064
8/2/2021, 2:04:26 PM HOOBS [ ERROR ] [HOOBS 27BA@GoveeH5179_4C70@@Current Relative Humidity] characteristic was supplied illegal value: number 420 exceeded maximum of 100
8/2/2021, 2:04:26 PM HOOBS [ DEBUG ] discovered e01220704c70 e01220704c70 e0:12:20:70:4c:70 disconnected -88
8/2/2021, 2:04:26 PM HOOBS [ DEBUG ] e01220704c70: 0188ec000101000a681064
8/2/2021, 2:04:28 PM HOOBS [ DEBUG ] discovered e01220704c70 e01220704c70 e0:12:20:70:4c:70 disconnected -81
8/2/2021, 2:04:28 PM HOOBS [ DEBUG ] e01220704c70: 0188ec000101000a681064
8/2/2021, 2:04:28 PM HOOBS [ DEBUG ] discovered e01220704c70 e01220704c70 e0:12:20:70:4c:70 disconnected -80
8/2/2021, 2:04:28 PM HOOBS [ DEBUG ] e01220704c70: 0188ec000101f609681064
8/2/2021, 2:04:28 PM HOOBS [ ERROR ] [HOOBS 27BA@GoveeH5179_4C70@@Current Relative Humidity] characteristic was supplied illegal value: number 420 exceeded maximum of 100
8/2/2021, 2:04:29 PM HOOBS [ DEBUG ] discovered e01220704c70 e01220704c70 e0:12:20:70:4c:70 disconnected -87
8/2/2021, 2:04:29 PM HOOBS [ DEBUG ] e01220704c70: 0188ec000101f609681064
8/2/2021, 2:04:29 PM HOOBS [ ERROR ] [HOOBS 27BA@GoveeH5179_4C70@@Current Relative Humidity] characteristic was supplied illegal value: number 420 exceeded maximum of 100
8/2/2021, 2:04:29 PM HOOBS [ DEBUG ] discovered e01220704c70 e01220704c70 e0:12:20:70:4c:70 disconnected -86
8/2/2021, 2:04:29 PM HOOBS [ DEBUG ] e01220704c70: 0188ec000101f609681064
8/2/2021, 2:04:29 PM HOOBS [ ERROR ] [HOOBS 27BA@GoveeH5179_4C70@@Current Relative Humidity] characteristic was supplied illegal value: number 420 exceeded maximum of 100
8/2/2021, 2:04:31 PM HOOBS [ DEBUG ] discovered e01220704c70 e01220704c70 e0:12:20:70:4c:70 disconnected -80
8/2/2021, 2:04:31 PM HOOBS [ DEBUG ] e01220704c70: 0188ec000101f609681064
8/2/2021, 2:04:31 PM HOOBS [ ERROR ] [HOOBS 27BA@GoveeH5179_4C70@@Current Relative Humidity] characteristic was supplied illegal value: number 420 exceeded maximum of 100
8/2/2021, 2:04:31 PM HOOBS [ DEBUG ] discovered e01220704c70 e01220704c70 e0:12:20:70:4c:70 disconnected -80
8/2/2021, 2:04:31 PM HOOBS [ DEBUG ] e01220704c70: 0188ec000101f609681064
8/2/2021, 2:04:31 PM HOOBS [ ERROR ] [HOOBS 27BA@GoveeH5179_4C70@@Current Relative Humidity] characteristic was supplied illegal value: number 420 exceeded maximum of 100
8/2/2021, 2:04:32 PM HOOBS [ DEBUG ] discovered e01220704c70 e01220704c70 e0:12:20:70:4c:70 disconnected -85
8/2/2021, 2:04:32 PM HOOBS [ DEBUG ] e01220704c70: 0188ec000101f609681064
8/2/2021, 2:04:32 PM HOOBS [ ERROR ] [HOOBS 27BA@GoveeH5179_4C70@@Current Relative Humidity] characteristic was supplied illegal value: number 420 exceeded maximum of 100
8/2/2021, 2:04:32 PM HOOBS [ DEBUG ] discovered e01220704c70 e01220704c70 e0:12:20:70:4c:70 disconnected -87
8/2/2021, 2:04:32 PM HOOBS [ DEBUG ] e01220704c70: 0188ec000101f609681064
8/2/2021, 2:04:32 PM HOOBS [ ERROR ] [HOOBS 27BA@GoveeH5179_4C70@@Current Relative Humidity] characteristic was supplied illegal value: number 420 exceeded maximum of 100
8/2/2021, 2:04:35 PM HOOBS [ DEBUG ] discovered e01220704c70 e01220704c70 e0:12:20:70:4c:70 disconnected -80
8/2/2021, 2:04:35 PM HOOBS [ DEBUG ] e01220704c70: 0188ec000101f609681064
8/2/2021, 2:04:35 PM HOOBS [ ERROR ] [HOOBS 27BA@GoveeH5179_4C70@@Current Relative Humidity] characteristic was supplied illegal value: number 420 exceeded maximum of 100
8/2/2021, 2:04:35 PM HOOBS [ DEBUG ] discovered e01220704c70 e01220704c70 e0:12:20:70:4c:70 disconnected -79
8/2/2021, 2:04:35 PM HOOBS [ DEBUG ] e01220704c70: 0188ec000101f609681064
8/2/2021, 2:04:35 PM HOOBS [ ERROR ] [HOOBS 27BA@GoveeH5179_4C70@@Current Relative Humidity] characteristic was supplied illegal value: number 420 exceeded maximum of 100
8/2/2021, 2:04:37 PM HOOBS [ DEBUG ] discovered e01220704c70 e01220704c70 e0:12:20:70:4c:70 disconnected -80
8/2/2021, 2:04:37 PM HOOBS [ DEBUG ] e01220704c70: 0188ec000101f609681064
8/2/2021, 2:04:37 PM HOOBS [ ERROR ] [HOOBS 27BA@GoveeH5179_4C70@@Current Relative Humidity] characteristic was supplied illegal value: number 420 exceeded maximum of 100
8/2/2021, 2:04:37 PM HOOBS [ DEBUG ] discovered e01220704c70 e01220704c70 e0:12:20:70:4c:70 disconnected -80
8/2/2021, 2:04:37 PM HOOBS [ DEBUG ] e01220704c70: 0188ec000101000a681064
8/2/2021, 2:04:40 PM HOOBS [ DEBUG ] discovered e01220704c70 e01220704c70 e0:12:20:70:4c:70 disconnected -79
8/2/2021, 2:19:44 PM HOOBS [ DEBUG ] e01220704c70: 0188ec000101000a541064
8/2/2021, 2:23:03 PM HOOBS [ DEBUG ] e01220704c70: 0188ec000101000a181064

```

**Additional context**
![Hoobs Plugin](https://user-images.githubusercontent.com/84479947/127926072-bcde58f5-b203-422c-a0b5-d4d986955028.png)
![Hoobs Dashboard](https://user-images.githubusercontent.com/84479947/127926088-91ec3a9d-1cf4-4192-b90a-b0dedd244086.png)

For some crazy reason HOOBS 4.0.98 shows my plugins on the Dashboard but say's I don't have any plugins installed when I go and view the Plugins > Plugins installed. I logged in using Windows 10. I just installed a Meross pluging and as you can see it is not listed as well.  I keep everything under the same bridge which I just call it HOOBS. I can see Featured and Popular plugins. I did try to reboot the system and even unplugged it for a few seconds.

**Comment by mkellsy** [comment]
Fixed in
GUI 4.0.84
Desktop 4.0.54

**Comment by James-Engel** [comment]
It still doesn’t work.  On Mon, Aug 2, 2021 at 8:15 PM Michael Kellsy ***@***.***> wrote:Fixed inGUI 4.0.84Desktop 4.0.54—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by James-Engel** [comment]
I have a newer version.  JimE From: Michael KellsySent: Monday, August 2, 2021 8:15 PMTo: hoobs-org/HOOBSCc: James-Engel; AuthorSubject: Re: [hoobs-org/HOOBS] My Plugins are not shown "No plugins installed. Install Plugin" (#1438) Fixed inGUI 4.0.84Desktop 4.0.54—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
