### ISSUE TITLE
NGINX Configuration Promise Had No Exit on Initilization

### ISSUE THREAD

**Issue by OfficialKaos** [hoobs-org/HOOBS#350]
**Description**

**Can't upgrade to V3 , this is the error message**

USER: hoobs
DIR: /usr/local/lib
CMD: sudo -E -n npm --no-update-notifier install --unsafe-perm homebridge-to-hoobs@latest

sudo: npm: command not found

Command failed. Please review log for details.

**Can't update Node, this is the error message**

hoobs@hoobs:/var/lib/homebridge $ hoobs-update
Installed: v10.16.3
Current Node.js LTS: v12.14.0
Updating Node.js to v12.14.0...
/usr/local/sbin/hoobs-update: line 15: npm: command not found

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
hoobs@hoobs:/var/lib/homebridge $ 

**Version**
Please include the version of HOOBS you are using.
2.1.1

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ x] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [xx ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ x] HOOBS Box
- [ ] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
Please include a list of the plugins you are using. We need to be able to find it on NPM. If the plugin is no published, please include a link to the repository.

homebridge-harmony v1.2.1 
homebridge-config-ui-x v4.6.6 

**Post your config**
This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`

* Remove any passwords from the config file. This is public.

```
{
    "bridge": {
        "name": "HOOBS",
        "username": "xx:xx:xx:xx:xx:xx",
        "port": 51826,
        "pin": "xxx-xx-xxx"
    },
    "description": "This file is used for plugin configuration.",
    "accessories": [],
    "platforms": [
        {
            "platform": "HarmonyHubWebSocket",
            "name": "Harmony Remote",
            "hubIP": "192.168.1.168",
            "otherPlatforms": [
                {
                    "name": "Harmony Hub",
                    "hubIP": "192.168.1.198"
                }
            ]
        },
        {
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "theme": "brown",
            "restart": "sudo -n systemctl restart homebridge homebridge-config-ui-x",
            "temp": "/sys/class/thermal/thermal_zone0/temp",
            "tempUnits": "c",
            "sudo": true,
            "standalone": true,
            "log": {
                "method": "custom",
                "command": "sudo -n journalctl -o cat -n 500 -f -u homebridge -u homebridge-config-ui-x"
            },
            "platform": "config"
        }
    ]
}
```

**Post your log**
You can get the log from the intercafe. This is in the Log section.

```
POST LOG HERE
```

**Additional context**

**Comment by mkellsy** [comment]
It looks like the to-hoobs plugin didn't get published. It is there now. You may need to run this in the terminal first.

```
sudo npm cache clear --force
```

**Comment by OfficialKaos** [comment]
Didn't work . I did a new install of 2.1.1 and started the migration process again

**Comment by mkellsy** [comment]
Can you run these commands.
```
node -v
```
```
npm -v
```
What does each say?

**Comment by mkellsy** [comment]
The hoobs-upgrade command doesn't upgrade HOOBS it only upgrades Node.

Here are the instructions on how to upgrade to HOOBS 3
https://github.com/hoobs-org/HOOBS/wiki/2.3-Upgrading-HOOBS

**Comment by OfficialKaos** [comment]
Running Node 10.16.0 
Latest attempt to upgrade is stating, for last 45mins is this normal? 

> ⠴ Configuring NGINX

**Comment by mkellsy** [comment]
Wait to see if it causes an error or succeeded.

**Comment by OfficialKaos** [comment]
ok thanks , will do

**Comment by OfficialKaos** [comment]
How many pi's running Hoobs V3.x.x can i have on the same network?
i currently have 4 on V2.1.1 and 1 on V3.1.9?

**Comment by mkellsy** [comment]
I found the issue. There is a new version 3.1.10 that fixes this. I am testing it here now.

**Comment by mkellsy** [comment]
Fixed in 3.1.10

**Comment by OfficialKaos** [comment]
still no change , shall I start over?

**Comment by mkellsy** [comment]
Yes, I found the issue and released 3.1.10. I tested a 2.1.1 -> 3.1.10 upgrade and it worked.

**Comment by OfficialKaos** [comment]
Upgrade woked but can't, install plugin?
Please see log


[12/22/2019, 7:48:34 PM] HOOBS listning on port 8080.[Homebridge] [12/22/2019, 7:48:36 PM] Loaded config.json with 0 accessories and 0 platforms.[Homebridge] [12/22/2019, 7:48:36 PM] ---[Homebridge] [12/22/2019, 7:48:37 PM] No plugins found. See the README for information on installing plugins.[Homebridge] [12/22/2019, 7:48:37 PM] Loading 0 platforms...[Homebridge] [12/22/2019, 7:48:37 PM] Loading 0 accessories...[Homebridge] X-HM://0023ISYWY5A5P[Homebridge] [12/22/2019, 7:48:37 PM] Service is running on port 51826.[Homebridge] [12/22/2019, 7:49:51 PM] Got SIGINT, shutting down service...[Homebridge] [12/22/2019, 7:49:53 PM] Loaded config.json with 0 accessories and 0 platforms.[Homebridge] [12/22/2019, 7:49:53 PM] ---[Homebridge] [12/22/2019, 7:49:53 PM] No plugins found. See the README for information on installing plugins.[Homebridge] [12/22/2019, 7:49:53 PM] Loading 0 platforms...[Homebridge] [12/22/2019, 7:49:53 PM] Loading 0 accessories...[Homebridge] X-HM://0023ISYWY5A5P[Homebridge] [12/22/2019, 7:49:53 PM] Service is running on port 51826.[Homebridge] [12/22/2019, 7:49:53 PM] Got SIGINT, shutting down service...Unhandled rejection Error: EACCES: permission denied, mkdir '/home/hoobs/.npm/_cacache/index-v5/bc/24'Unhandled rejection Error: EACCES: permission denied, mkdir '/home/hoobs/.npm/_cacache/index-v5/15/2d'npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2019-12-22T19_50_03_414Z-debug.log[12/22/2019, 7:50:03 PM] Installed "homebridge-zp" package.[Homebridge] [12/22/2019, 7:50:04 PM] Loaded config.json with 0 accessories and 0 platforms.[Homebridge] [12/22/2019, 7:50:04 PM] ---[Homebridge] [12/22/2019, 7:50:04 PM] No plugins found. See the README for information on installing plugins.[Homebridge] [12/22/2019, 7:50:04 PM] Loading 0 platforms...[Homebridge] [12/22/2019, 7:50:04 PM] Loading 0 accessories...[Homebridge] X-HM://0023ISYWY5A5P[Homebridge] [12/22/2019, 7:50:04 PM] Service is running on port 51826.

**Comment by OfficialKaos** [comment]
Please see error message received after upgrade attempt
Node was updated to 10.17.0

> Configuring NGINX

  Checking Configuration
npm WARN ws@7.2.1 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.2.1 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.

+ @hoobs/hoobs@3.1.10
updated 1 package in 44.202s
npm WARN saveError ENOENT: no such file or directory, open '/usr/local/lib/package.json'

**Comment by mkellsy** [comment]
I going to have to schedule a remote session with you. I am using Bomgar from work.

1. Go to https://remote.encompass8.com
2. In the Session Key section enter **7447613**
3. Click Submit

**Comment by mkellsy** [comment]
I lost the connection
Here's a new code **6970702**

**Comment by OfficialKaos** [comment]
Sorry Mike I lost connection ,don't know why

**Comment by mkellsy** [comment]
Lost you again. Here is a new code
**0289054**

**Comment by mkellsy** [comment]
This was an issue with NPM. NPM had some stuck linking so Node-GYP wouldn't compile. Here's how I fixed it.

1. Get the current NPM version
```
npm -v
```

2. Reinstall NPM
```
sudo npm install -g npm@results from above
```

3. Run the upgrade again

**Comment by OfficialKaos** [comment]
Tried running 

> sudo rm -fR .npm/

 sudo npm cache clear --force 

still not allowing pluggins?

**Comment by mkellsy** [comment]
Is it any plugin?
When you run
```
npm get prefix
```
What does it say?

**Comment by OfficialKaos** [comment]
/usr/local

┌─────────────────────────────────────────────────────────┐
│                 npm update check failed                 │
│           Try running with sudo or get access           │
│          to the local update config store via           │
│ sudo chown -R $USER:$(id -gn $USER) /home/hoobs/.config │
└─────────────────────────────────────────────────────────┘

**Comment by mkellsy** [comment]
Let me hop on your computer, I think I know what's wrong.

**Comment by mkellsy** [comment]
Another device with a root locked npm cache.

**Comment by OfficialKaos** [comment]
All fixed here now
Thank you
