### ISSUE TITLE
ffmpeg issue

### ISSUE THREAD

**Issue by shayfunk** [hoobs-org/HOOBS#474]
Did fresh install of HOOBS and verified ffmpeg libraries. Can see camera in VLC but no feed in HomeKit

**Comment by askovi** [comment]
Please follow the issue template

**Comment by shayfunk** [comment]
[logs (1).txt](https://github.com/hoobs-org/HOOBS/files/4177388/logs.1.txt)

**Comment by askovi** [comment]
Server returned 401 Unauthorized (authorization failed)

Your username or password is incorrect or you supplied them wrong in the rtsp url.

Should be rtsp://user:password@ip

**Comment by shayfunk** [comment]
Version
3.1.20

Did you upgrade
Please let us know if you upgraded from a previous version.

[ ] Yes
{X} No
Pervious version
If you upgraded, please let us know your previous version.

Fresh install of 3.1.20

Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.

Yes
[X ] No
What device are you using?
Please let us know the device you are running HOOBS on.
Raspberry Pi 4B 

HOOBS Box
[X ] HOOBS SD Card


List your plugins
Camera FFMPEG
0.1.14 published 10/31/2019

Post your config

**Comment by shayfunk** [comment]
nevermind...got it.

**Comment by shayfunk** [comment]
only the snapshot working
[logs (2).txt](https://github.com/hoobs-org/HOOBS/files/4177415/logs.2.txt)


> Server returned 401 Unauthorized (authorization failed)
> 
> Your username or password is incorrect or you supplied them wrong in the rtsp url.
> 
> Should be rtsp://user:password@ip

yeah i corrected that and can see in vlc if copy and paste

**Comment by askovi** [comment]
Lower your maxFPS to 15
add  "packetSize": 188
save and test. If still not streaming, try changing the vcodec to
"vcodec": "h264_omx"

**Comment by shayfunk** [comment]
> Lower your maxFPS to 15
> add "packetSize": 188
> save and test. If still not streaming, try changing the vcodec to
> "vcodec": "h264_omx"

I thought we weren't supposed to use h264_omx? just from reading other comments because already in that format? idk...but now it's working Sorry to waste your time. thanks

**Comment by askovi** [comment]
vcodec:copy doesn't re-encode the video so it can run smoother but it doesn't always work if the format is not right for Homekit. h264_omx re-encodes it properly

**Comment by shayfunk** [comment]
> vcodec:copy doesn't re-encode the video so it can run smoother but it doesn't always work if the format is not right for Homekit. h264_omx re-encodes it properly

okay thanks. i am trying to learn what all these different parameters do. i appreciate the explanation.
