### ISSUE TITLE
NPM SSL errors, unable to install any plugins

### ISSUE THREAD

**Issue by Pascal27** [hoobs-org/HOOBS#552]
**Description**
I am unable to install any new plugin and always getting an install failed error.

**Version**
3.1.26

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [x] Yes
- [ ] No

**Pervious version**
3.1.20

**Did you originally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [x] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [x] Custom Install

**If this is a custom install, what's your operating system?**
Raspberry Pi 3 Model B

**List your plugins**
No plugin installed so far

**Post your config**
```
{
    "server": {
        "port": 8080,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYGM10",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "celsius",
        "country_code": "DE",
        "postal_code": "",
        "latitude": "",
        "longitude": ""
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "75:6D:9E:5A:36:03"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": []
}
```

**Post your log**
```
[4/16/2020, 7:10:42 AM] HOOBS listening on port 8080.
[Homebridge] [4/16/2020, 7:10:43 AM] Loaded config.json with 0 accessories and 0 platforms.
[Homebridge] [4/16/2020, 7:10:43 AM] No plugins found.
[Homebridge] [4/16/2020, 7:10:43 AM] Loading 0 platforms...
[Homebridge] [4/16/2020, 7:10:43 AM] Loading 0 accessories...
[Homebridge] [4/16/2020, 7:10:43 AM] Homebridge is running on port 51826.
[Homebridge] [4/16/2020, 7:11:14 AM] Got SIGINT, shutting down Homebridge...
npm
 ERR! code EPROTO
npm ERR! errno EPROTO
npm
ERR! request to https://registry.npmjs.org/@hoobs%2froborock failed, reason: write EPROTO 1995826192:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
npm ERR!
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2020-04-16T13_11_23_675Z-debug.log
[Homebridge] [4/16/2020, 7:11:24 AM] Loaded config.json with 0 accessories and 0 platforms.
[Homebridge] [4/16/2020, 7:11:24 AM] No plugins found.
[Homebridge] [4/16/2020, 7:11:24 AM] Loading 0 platforms...
[Homebridge] [4/16/2020, 7:11:24 AM] Loading 0 accessories...
[Homebridge] [4/16/2020, 7:11:24 AM] Homebridge is running on port 51826.
```

**Additional context**
I have made a complete fresh reinstall of HOOBS because I was no longer able to open it.

Additionally to the issue above I am getting some crashes of HOOBS when opening some tabs of the plugins menu such as the search there, might be related to it.

**Comment by mkellsy** [comment]
This looks like a corrupt NPM.
https://github.com/npm/npm/issues/20321

You may need to reinstall Node

**Comment by mkellsy** [comment]
I just released 3.1.27
This issue has been fixed.
I recommend updating.

**Comment by Pascal27** [comment]
Thanks for your help!

Sadly I am still having the same issue with 3.1.27. Do you know any way to fix it? I have tried to reinstall it again but still getting the same error when installing new plugins.

**Comment by mkellsy** [comment]
This looks like an issue with npm. Are you behind a proxy?
Check this out https://npm.community/t/ssl-routineswrong-version-number/6048

**Comment by Pascal27** [comment]
No, I am not behind a proxy.

**Comment by mkellsy** [comment]
I can help you to reinstall Node. I need a bit of information first.

Can you run these commands and post the results
```
uname
```

And then
```
uname -m
```

And then this (if nothing returns let me know)
```
test -f /usr/local/bin/node && echo "node exists"
```

**Comment by Pascal27** [comment]
Thank you very much for your help! Here are the results you were asking for:

```
> uname
Linux
> uname -m
armv7l
> test -f /usr/local/bin/node && echo "node exists"
node exists
```

**Comment by mkellsy** [comment]
Ok these commands will reinstall Node
```
curl -k -O https://nodejs.org/dist/v12.16.2/node-v12.16.2-linux-armv7l.tar.gz
sudo tar -xzf ./node-v12.16.2linux-armv7l.tar.gz -C /usr/local --strip-components=1 --no-same-owner
rm -f ./node-v12.16.2-linux-armv7l.tar.gz
npm config set -g prefix /usr/local
```

This probably is a newer version so now you need to reinstall HOOBS Core
```
sudo npm uninstall -g @hoobs/hoobs
sudo npm install -g --unsafe-perm @hoobs/hoobs
```

Then restart HOOBS
```
sudo hoobs service restart
```

> Note it is best to do this from an SSH terminal.

**Comment by Pascal27** [comment]
I get the following error when using
```
sudo tar -xzf ./node-v12.16.2linux-armv7l.tar.gz -C /usr/local --strip-components=1 --no-same-owner
```

```
tar (child): ./node-v12.16.2linux-armv7l.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

**Comment by mkellsy** [comment]
Missd a dash in the untar command.
```
curl -k -O https://nodejs.org/dist/v12.16.2/node-v12.16.2-linux-armv7l.tar.gz
sudo tar -xzf ./node-v12.16.2-linux-armv7l.tar.gz -C /usr/local --strip-components=1 --no-same-owner
rm -f ./node-v12.16.2-linux-armv7l.tar.gz
npm config set -g prefix /usr/local
```

**Comment by Pascal27** [comment]
Thank you! That worked now but sadly I get another error now:
```
> sudo npm uninstall -g @hoobs/hoobs

npm ERR! code ENOENT
npm ERR! syscall stat
npm ERR! path /hoobs-core.tgz
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, stat '/hoobs-core.tgz'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-23T16_42_04_163Z-debug.log
```

**Comment by mkellsy** [comment]
This can be an issue with the build process. This should get you squared away.

```
sudo npm install -g --unsafe-perm @hoobs/hoobs
sudo npm uninstall -g @hoobs/hoobs
sudo npm install -g --unsafe-perm @hoobs/hoobs
```

**Comment by Pascal27** [comment]
Thanks again for your help!
Unfortunately another error:

```
> sudo npm install -g --unsafe-perm @hoobs/hoobs
```

```node.js
npm ERR! code EPROTO
npm ERR! errno EPROTO
npm ERR! request to https://registry.npmjs.org/@hoobs%2fhoobs failed, reason: write EPROTO 1995544224:error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1550:SSL alert number 70
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-24T16_41_56_562Z-debug.log
```

**Comment by mkellsy** [comment]
I did some digging and  think your openssl is out of date. NPM does use TLS 1.2.
You should run these commands
```
sudo apt-get update
sudo apt-get install --only-upgrade openssl
sudo apt-get install --only-upgrade libssl-dev
```
> Source https://support.stripe.com/questions/upgrade-openssl-to-support-tls-1-2

**Comment by Pascal27** [comment]
Good point! Looks like the problem. It seems `libssl-dev` is not installed though?

```
> sudo apt-get install --only-upgrade libssl-dev
```

```node.js
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Skipping libssl-dev, it is not installed and only upgrades are requested.
0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.
```

**Comment by mkellsy** [comment]
Just remove the --only-upgrade flag.

**Comment by Pascal27** [comment]
There is still a warning for an outdated protocol version even though I have updated openssl as mentioned above?

 ```
> sudo npm install -g --unsafe-perm @hoobs/hoobs
```

```node.js
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EPROTO: request to https://registry.npmjs.org/@hoobs%2fhoobs failed, reason: write EPROTO 1995904672:error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1550:SSL alert number 70\n
```

**Comment by mkellsy** [comment]
This is wired, it is almost like Node is missing some system prerequisites. Do you have anything else setup on this?

If not, it might be best to start with a prebuild image. You can download it here.
https://github.com/hoobs-org/hoobs-build/releases/download/v3.1.27/HOOBS-3.1.27-ARM7.zip

You can flash the SD Card with the Balina etcher.
https://www.balena.io/etcher/

**Comment by Pascal27** [comment]
Nothing else setup on the Raspberry Pi.

I have already tried it with the prebuilt image but sadly getting the same issue.

The only other thing I could try is to install it on a Synology NAS via Docker, not sure if that doesn't have the problem.

**Comment by mkellsy** [comment]
If you are getting the same issue with pre-built SD cards which are teated, I would say there is something on your network or internet provider that is proxying your connections to npm. I can not say if the docker image wouldn't act the same.

Are you using a VPN? Pi-Hole? Or anything that would otherwise filter your internet. If you do this is a proxy.

**Comment by Pascal27** [comment]
Sorry for the late reply, was a bit busy.

You are indeed right that this is a problem an my network and not an issue with HOOBS or HomeBridge. Getting the same problem with other HomeBridge setups.

I am not using a VPN or Pi-Hole and don't know anything that would filter my internet. I have also asked my provider and they said the they are not proxying my connection.

I have also tried using a different DNS server but still getting the same issue. https://npmjs.com/ opens without a problem.

**Comment by BobbySlope** [comment]
closing for now, if issue still persists please reopen and provide more info
