### ISSUE TITLE
Weather Forecast not Showing

### ISSUE THREAD

**Issue by MatsA** [hoobs-org/HOOBS#95]
Hi !

Been using Homebridge, the raw version, a while and written some posts about it https://pysselilivet.blogspot.com/search/label/HomeKit

Some thoughts/questions, using RPi 4

1/ Did an image installation with V2.1.1 and then upgrading with ”Homebridge-config-ui-hoobs”
    After installing and reboot it was still on the old V2 interface ??
    Via ”Terminal” I did a manual install, and 1 update was done, and after a reboot I’m on the V2
    version !
2/ Saw that ”Terminal” will be back in Beta 29, but still wonder how You log on with ssh ? User ”hoobs” but what password ? 
3/ In ”Edit Accessories” You can make an accessorie ”Not visible”, but how do You make it visible again ?
4/ Should there bee a forecast ? 
5/ I think it would have been nice if You didn’t use the same config as the ”original” Homebridge

"bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
6/ Also think that clicking on the Homebridge symbol in the upper left corner should take You to the Status screen. Pretty standard ?!

As said a nice package with good documentation, not so common ;-)

/Mats

![Hoobs](https://user-images.githubusercontent.com/16189982/63937617-138b9a80-ca63-11e9-98e0-b247df5c5fbc.png)

**Comment by mkellsy** [comment]
The default SSH username is hoobs and the password is hoobdadmin.

To un-hide an accessory, just add it to a room, I don't hide it from the add to room list.

There is a bug with the forecast, fixing soon, it's still a beta. 2 days old :)

As for the Homebridge config, we still use Homebridge under the hood with mods to load plugins that don't start with homebridge-. Mainly so we can use NPM scoped packages like @hoobs/nest.

Thank You for your support.

**Comment by MatsA** [comment]
Thanks for quick support ! Nice !

3/ If You hide an, not assigned, accessory it seems to disappear ?? 
5/ My point was that if You already have one Hombridge up and running and add Hoobs, there will be a conflict. Avoided using another "username"/"port"/"pin"

**Comment by mkellsy** [comment]
Possible, but HOOBS is a different application, so you can login go to the config and generate a new username and change the bridge name, and it will fire up.

**Comment by mkellsy** [comment]
Fixed in 3.0.0-beta.33

**Comment by BobbySlope** [comment]
Still don't work on beta 38 - does not hurry just to keep track
24h format and Country/City settings for weather
<img width="759" alt="Screenshot 2019-08-31 at 13 47 25" src="https://user-images.githubusercontent.com/50763727/64063562-ed4a3400-cbf5-11e9-9191-e6a765e9d476.png">

**Comment by mkellsy** [comment]
Clear you cookies

**Comment by BobbySlope** [comment]
doesn't solve the issue

**Comment by mkellsy** [comment]
Open weather doesn't have an option for the time.

I must restrict the number of calls to open weather. We are only allowed 60 calls a minute. Any more and it is blocked. To remove this block it will cost $$$$$$. Yes I mean big bucks $$$$$$$$$$$$$$.

All the other weather services that have an API cost even more and don't have a community option. They are aware of us and what we are doing, so they may give us the benefit of doubt if we go over, as long as we are making an attempt to restrict the number of calls.

I dropped the timeout to 15 minutes. We should be OK.
Fixed in 3.0.0-beta.39
